/* eslint-disable react/no-unescaped-entities */
"use client";
import React from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";

export default function TermsOfService() {
  const router = useRouter();
  
  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Navigation Bar */}
      <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container mx-auto px-4 md:px-8 flex h-14 items-center">
          <button onClick={() => router.back()} className="flex items-center space-x-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="h-4 w-4" />
            <span>Back</span>
          </button>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto py-12 px-4 md:px-8 max-w-4xl">
        <div className="space-y-8">
          <div>
            <h1 className="text-4xl font-bold tracking-tight mb-4 text-primary">Terms of Service</h1>
            <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
          </div>

          <div className="prose prose-slate dark:prose-invert max-w-none space-y-6 text-foreground/90">
            <section>
              <h2 className="text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing and using Arovia.AI (the "Service"), you agree to be bound by these Terms of Service ("Terms") and our Privacy Policy. If you do not agree to these Terms, you may not access or use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mt-8 mb-4">2. Nature of the AI Chatbot Service</h2>
              <p>
                Arovia.AI provides an AI-powered conversational assistant designed for educational and informational purposes surrounding pain management and general wellness. The responses you receive are generated by artificial intelligence, not a human professional. As detailed in our Medical Disclaimer, the Service is <strong>not a medical device, nor is it a substitute for professional medical advice, diagnosis, or treatment.</strong>
              </p>
              <p>
                The AI may occasionally produce inaccurate, misleading, or fabricated information (often referred to as "hallucinations"). You are solely responsible for cross-referencing and verifying any suggestions with a licensed clinical professional before acting on them.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mt-8 mb-4">3. User Accounts & Data</h2>
              <p>
                When you create an account with us, you must provide accurate, complete, and current information. You must be at least 18 years of age, or the age of majority under the Indian Contract Act, 1872, to form a binding contract. You are responsible for safeguarding your password and tracking your chat history safely. Because the core function of the application is a conversational AI, any text prompts, responses, and session metadata will be processed by our system to provide you with the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mt-8 mb-4">4. Acceptable AI Usage</h2>
              <p>
                You agree not to use the Service or its chatbot interface:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>In any way that violates any applicable national or state law in India, including the Information Technology Act, 2000.</li>
                <li>To attempt to independently diagnose or treat a severe medical condition without physician consultation in accordance with Telemedicine Practice Guidelines, or prompt the AI to issue prescriptive drug advice.</li>
                <li>To perform automated data scraping, reverse-engineer the underlying LLM models, or attempt to extract system prompts through jailbreaking techniques.</li>
                <li>To submit malicious code, highly illegal content, or excessively explicit material into the chat inputs.</li>
                <li>To engage in any other conduct that degrades the AI infrastructure or harms other users of the Service.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mt-8 mb-4">5. Intellectual Property</h2>
              <p>
                The Service and its original content, features, and functionality are and will remain the exclusive property of Arovia.AI and its licensors. The Service is protected by copyright, trademark, and other laws. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Arovia.AI.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mt-8 mb-4">6. Limitation of Liability</h2>
              <p>
                In no event shall Arovia.AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mt-8 mb-4">7. Governing Law & Jurisdiction</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. You agree that any legal action or proceeding arising out of or related to these Terms or the Service shall be instituted exclusively in the courts located in New Delhi, India.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mt-8 mb-4">8. Changes to Terms</h2>
              <p>
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
              </p>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
