"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones, configureBoneyard } from 'boneyard-js/react'

import _doctor_calendar from './doctor-calendar.bones.json'
import _appointments_list from './appointments-list.bones.json'

configureBoneyard({"color":"#e0e0e0","darkColor":"rgba(255,255,255,0.08)","animate":"pulse"})

registerBones({
  "doctor-calendar": _doctor_calendar,
  "appointments-list": _appointments_list,
})
